[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://seu-backend.onrender.com"
  REACT_APP_ENV = "production"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://seu-backend.onrender.com"
  REACT_APP_ENV = "preview" 